/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Entidades.Animal;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riosr
 */
public class GUIAnimales extends javax.swing.JFrame {

    private control control;
    /**
     * Creates new form GUIAnimales
     * @param control
     */
    public GUIAnimales(control control) {
        this.control = control;
        initComponents();
        llenarTablaAnimales();
    }
    
    public void llenarTablaAnimales() {
        List<Animal> listaAnimales = control.getAnimalBO().obtenerTodosLosAnimales();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Animal");
        modelo.addColumn("Identificación");
        modelo.addColumn("Sexo");
        modelo.addColumn("Año Nacimiento");
        modelo.addColumn("Especie");
        modelo.addColumn("Zoológico");

        for (Animal a : listaAnimales) {
            Object[] fila = new Object[6];
            fila[0] = a.getIdAnimal();
            fila[1] = a.getIdentificacion();
            fila[2] = a.getSexo();
            fila[3] = a.getAnioNacimiento();

            // Obtener el nombre de la especie y zoológico
            fila[4] = control.getEspecieBO().obtenerEspeciePorId(a.getIdEspecie()).getNombreVulgar();
            fila[5] = control.getZoologicoBO().obtenerZoologicoPorId(a.getIdZoologico()).getNombre();

            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAnimalesID = new javax.swing.JTextField();
        txtAnimalesIdentificacion = new javax.swing.JTextField();
        txtAnimalesSexo = new javax.swing.JTextField();
        txtAnimalesAñoNacimiento = new javax.swing.JTextField();
        btnAnimalesGuardar = new javax.swing.JButton();
        btnAnimalesCancelar = new javax.swing.JButton();
        txtAnimalesBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAnimalesBuscar = new javax.swing.JButton();
        btnAnimalesEditar = new javax.swing.JButton();
        btnAnimalesEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAnimalRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbxAnimalesEspecie = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 153));
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 153));
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 153));
        jLabel4.setText("Año de Nacimiento:");

        txtAnimalesID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalesIDActionPerformed(evt);
            }
        });

        txtAnimalesIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalesIdentificacionActionPerformed(evt);
            }
        });

        txtAnimalesSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalesSexoActionPerformed(evt);
            }
        });

        txtAnimalesAñoNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalesAñoNacimientoActionPerformed(evt);
            }
        });

        btnAnimalesGuardar.setBackground(new java.awt.Color(204, 255, 153));
        btnAnimalesGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesGuardar.setText("Guardar");
        btnAnimalesGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesGuardarActionPerformed(evt);
            }
        });

        btnAnimalesCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnAnimalesCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesCancelar.setText("Cancelar");
        btnAnimalesCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesCancelarActionPerformed(evt);
            }
        });

        txtAnimalesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnimalesBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Animales", "Identificación", "Sexo", "Año Nacimiento", "Id Especie", "Id Zoologico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAnimalesBuscar.setBackground(new java.awt.Color(153, 204, 255));
        btnAnimalesBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesBuscar.setText("Buscar");
        btnAnimalesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesBuscarActionPerformed(evt);
            }
        });

        btnAnimalesEditar.setBackground(new java.awt.Color(255, 255, 153));
        btnAnimalesEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesEditar.setText("Editar");
        btnAnimalesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesEditarActionPerformed(evt);
            }
        });

        btnAnimalesEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnAnimalesEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalesEliminar.setText("Eliminar");
        btnAnimalesEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalesEliminarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 153));
        jLabel6.setText("Animales");

        btnAnimalRegresar.setBackground(new java.awt.Color(255, 255, 153));
        btnAnimalRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnimalRegresar.setText("Regresar");
        btnAnimalRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnimalRegresarMouseClicked(evt);
            }
        });
        btnAnimalRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalRegresarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 153));
        jLabel5.setText("Especie:");

        cmbxAnimalesEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especie", "Especie 2", "Especie 3" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAnimalesID)
                                    .addComponent(txtAnimalesIdentificacion)
                                    .addComponent(txtAnimalesSexo)
                                    .addComponent(txtAnimalesAñoNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(cmbxAnimalesEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnAnimalesGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnimalesCancelar)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(txtAnimalesBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAnimalesEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(btnAnimalesEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(btnAnimalesBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                    .addComponent(btnAnimalRegresar))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnimalesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnimalesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnimalesEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnAnimalesEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(btnAnimalRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAnimalesID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAnimalesIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAnimalesSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbxAnimalesEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtAnimalesAñoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAnimalesGuardar)
                                .addComponent(btnAnimalesCancelar)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnimalesIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalesIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalesIdentificacionActionPerformed

    private void btnAnimalesGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesGuardarActionPerformed

    private void btnAnimalesCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesCancelarActionPerformed

    private void btnAnimalesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesBuscarActionPerformed

    private void btnAnimalesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesEditarActionPerformed

    private void btnAnimalesEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalesEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesEliminarActionPerformed

    private void txtAnimalesIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalesIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalesIDActionPerformed

    private void txtAnimalesSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalesSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalesSexoActionPerformed

    private void txtAnimalesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalesBuscarActionPerformed

    private void txtAnimalesAñoNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnimalesAñoNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnimalesAñoNacimientoActionPerformed

    private void btnAnimalRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalRegresarActionPerformed

    private void btnAnimalRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalRegresarMouseClicked
        control.navegarGUIMenuPrincipal(this);
    }//GEN-LAST:event_btnAnimalRegresarMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimalRegresar;
    private javax.swing.JButton btnAnimalesBuscar;
    private javax.swing.JButton btnAnimalesCancelar;
    private javax.swing.JButton btnAnimalesEditar;
    private javax.swing.JButton btnAnimalesEliminar;
    private javax.swing.JButton btnAnimalesGuardar;
    private javax.swing.JComboBox<String> cmbxAnimalesEspecie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAnimalesAñoNacimiento;
    private javax.swing.JTextField txtAnimalesBuscar;
    private javax.swing.JTextField txtAnimalesID;
    private javax.swing.JTextField txtAnimalesIdentificacion;
    private javax.swing.JTextField txtAnimalesSexo;
    // End of variables declaration//GEN-END:variables
}
