/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Entidades.Especie;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author riosr
 */
public class GUIEspecies extends javax.swing.JFrame {

    /**
     * Creates new form GUIEspecies
     */
    private control control;
    public GUIEspecies(control control) {
        this.control = control;
        initComponents();
        llenarTabla();
    }
    
       public void llenarTabla() {
        List<Especie> listaEspecies = control.getEspecieBO().listarEspecies();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Especies");
        modelo.addColumn("Nombre Vulgar");
        modelo.addColumn("Nombre Científico");
        modelo.addColumn("Familia");
        modelo.addColumn("Peligro de Extinción");
        for (Especie e : listaEspecies) {
            Object[] fila = new Object[5];
            fila[0] = e.getIdEspecie();
            fila[1] = e.getNombreVulgar();
            fila[2] = e.getNombreCientifico();
            fila[3] = e.getFamilia();
            fila[4] = e.isPeligroExtincion() ? "Sí" : "No";
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEspecieID = new javax.swing.JTextField();
        txtEspecieNombreVulgar = new javax.swing.JTextField();
        txtEspecieNombreCientifico = new javax.swing.JTextField();
        txtEspecieFamilia = new javax.swing.JTextField();
        btnEspecieGuardar = new javax.swing.JButton();
        btnEspecieCancelar = new javax.swing.JButton();
        txtEspeciesBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEspecieBuscar = new javax.swing.JButton();
        btnEspecieEditar = new javax.swing.JButton();
        btnEspecieEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnEspecieRegresar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 153));
        jLabel2.setText("Nombre Vulgar:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 153));
        jLabel3.setText("Nombre Cientifico:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 153));
        jLabel4.setText("Familia:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 153));
        jLabel5.setText("Peligro de Extinción:");

        txtEspecieID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieIDActionPerformed(evt);
            }
        });

        txtEspecieNombreVulgar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieNombreVulgarActionPerformed(evt);
            }
        });

        txtEspecieNombreCientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieNombreCientificoActionPerformed(evt);
            }
        });

        txtEspecieFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieFamiliaActionPerformed(evt);
            }
        });

        btnEspecieGuardar.setBackground(new java.awt.Color(204, 255, 153));
        btnEspecieGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieGuardar.setText("Guardar");
        btnEspecieGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieGuardarActionPerformed(evt);
            }
        });

        btnEspecieCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnEspecieCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieCancelar.setText("Cancelar");
        btnEspecieCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieCancelarActionPerformed(evt);
            }
        });

        txtEspeciesBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspeciesBuscarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Especies", "Nomre Vulgar", "Nombre Cientifico", "Familia", "Peligro de Extincion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnEspecieBuscar.setBackground(new java.awt.Color(153, 204, 255));
        btnEspecieBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieBuscar.setText("Buscar");
        btnEspecieBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieBuscarActionPerformed(evt);
            }
        });

        btnEspecieEditar.setBackground(new java.awt.Color(255, 255, 153));
        btnEspecieEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieEditar.setText("Editar");
        btnEspecieEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieEditarActionPerformed(evt);
            }
        });

        btnEspecieEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEspecieEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieEliminar.setText("Eliminar");
        btnEspecieEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieEliminarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 153));
        jLabel6.setText("Especies");

        btnEspecieRegresar.setBackground(new java.awt.Color(255, 255, 153));
        btnEspecieRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEspecieRegresar.setText("Regresar");
        btnEspecieRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspecieRegresarMouseClicked(evt);
            }
        });
        btnEspecieRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspecieRegresarActionPerformed(evt);
            }
        });

        jCheckBox1.setMaximumSize(new java.awt.Dimension(30, 30));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(30, 30));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(30, 30));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEspecieID)
                                    .addComponent(txtEspecieNombreVulgar)
                                    .addComponent(txtEspecieNombreCientifico)
                                    .addComponent(txtEspecieFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnEspecieGuardar)
                        .addGap(99, 99, 99)
                        .addComponent(btnEspecieCancelar)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(txtEspeciesBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEspecieEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspecieEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspecieBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspecieRegresar))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspeciesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEspecieBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEspecieID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspecieNombreVulgar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspecieNombreCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEspecieFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEspecieGuardar)
                            .addComponent(btnEspecieCancelar)
                            .addComponent(btnEspecieRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEspecieEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnEspecieEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecieNombreVulgarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieNombreVulgarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieNombreVulgarActionPerformed

    private void btnEspecieGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieGuardarActionPerformed
        // TODO add your handling code here:
        Especie nuevaEspecie = new Especie();
        nuevaEspecie.setNombreVulgar(txtEspecieNombreVulgar.getText());
        nuevaEspecie.setNombreCientifico(txtEspecieNombreCientifico.getText());
        nuevaEspecie.setFamilia(txtEspecieFamilia.getText());
        nuevaEspecie.setPeligroExtincion(jCheckBox1.isSelected());
        
        control.getEspecieBO().registrarEspecie(nuevaEspecie);
        
        llenarTabla();
    }//GEN-LAST:event_btnEspecieGuardarActionPerformed

    private void btnEspecieBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspecieBuscarActionPerformed

    private void btnEspecieEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspecieEditarActionPerformed

    private void btnEspecieEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspecieEliminarActionPerformed

    private void btnEspecieCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEspecieCancelarActionPerformed

    private void txtEspeciesBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspeciesBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspeciesBuscarActionPerformed

    private void txtEspecieIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieIDActionPerformed

    private void txtEspecieNombreCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieNombreCientificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieNombreCientificoActionPerformed

    private void txtEspecieFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieFamiliaActionPerformed

    private void btnEspecieRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecieRegresarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnEspecieRegresarActionPerformed

    private void btnEspecieRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecieRegresarMouseClicked
        // TODO add your handling code here:
        control.navegarGUIMenuPrincipal(this);
        
    }//GEN-LAST:event_btnEspecieRegresarMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspecieBuscar;
    private javax.swing.JButton btnEspecieCancelar;
    private javax.swing.JButton btnEspecieEditar;
    private javax.swing.JButton btnEspecieEliminar;
    private javax.swing.JButton btnEspecieGuardar;
    private javax.swing.JButton btnEspecieRegresar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEspecieFamilia;
    private javax.swing.JTextField txtEspecieID;
    private javax.swing.JTextField txtEspecieNombreCientifico;
    private javax.swing.JTextField txtEspecieNombreVulgar;
    private javax.swing.JTextField txtEspeciesBuscar;
    // End of variables declaration//GEN-END:variables
}
