/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author riosr
 */
public class GUIMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenuPrincipal
     */
    private control control;
    public GUIMenuPrincipal(control control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuZoologicos = new javax.swing.JButton();
        btnMenuAnimales = new javax.swing.JButton();
        btnMenuEspecies = new javax.swing.JButton();
        btnMenuSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setText("PlanetaAnimal");

        btnMenuZoologicos.setBackground(new java.awt.Color(255, 255, 153));
        btnMenuZoologicos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuZoologicos.setForeground(new java.awt.Color(0, 51, 51));
        btnMenuZoologicos.setText("Zoologicos");
        btnMenuZoologicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuZoologicosMouseClicked(evt);
            }
        });
        btnMenuZoologicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuZoologicosActionPerformed(evt);
            }
        });

        btnMenuAnimales.setBackground(new java.awt.Color(255, 255, 153));
        btnMenuAnimales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuAnimales.setForeground(new java.awt.Color(0, 51, 51));
        btnMenuAnimales.setText("Animales");
        btnMenuAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuAnimalesMouseClicked(evt);
            }
        });
        btnMenuAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuAnimalesActionPerformed(evt);
            }
        });

        btnMenuEspecies.setBackground(new java.awt.Color(255, 255, 153));
        btnMenuEspecies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuEspecies.setForeground(new java.awt.Color(0, 51, 51));
        btnMenuEspecies.setText("Especies");
        btnMenuEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuEspeciesMouseClicked(evt);
            }
        });
        btnMenuEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEspeciesActionPerformed(evt);
            }
        });

        btnMenuSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnMenuSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenuSalir.setText("Salir");
        btnMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuSalirMouseClicked(evt);
            }
        });
        btnMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenuEspecies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnMenuZoologicos, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(btnMenuAnimales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(btnMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuZoologicos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnMenuAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnMenuEspecies, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnMenuSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuAnimalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuAnimalesActionPerformed

    private void btnMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuSalirActionPerformed

    private void btnMenuZoologicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuZoologicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuZoologicosActionPerformed

    private void btnMenuEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEspeciesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuEspeciesActionPerformed

    private void btnMenuZoologicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuZoologicosMouseClicked
        control.navegarGUIZoologico(this);
    }//GEN-LAST:event_btnMenuZoologicosMouseClicked

    private void btnMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuSalirMouseClicked
        control.salirPrograma(this);
    }//GEN-LAST:event_btnMenuSalirMouseClicked

    private void btnMenuAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuAnimalesMouseClicked
        control.navegarGUIAnimales(this);
    }//GEN-LAST:event_btnMenuAnimalesMouseClicked

    private void btnMenuEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuEspeciesMouseClicked
        control.navegarGUIEspecies(this);
    }//GEN-LAST:event_btnMenuEspeciesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuAnimales;
    private javax.swing.JButton btnMenuEspecies;
    private javax.swing.JButton btnMenuSalir;
    private javax.swing.JButton btnMenuZoologicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
